const booksList = [
   {
      id: '1',
      title: 'Eski Türkler',
      description: 'Netice itibariyle kadim Türkler insanlık tarihinde çok geniş ve önemli bir yer tutmuştur ama günümüze kadar bu milletin tarihi tam olarak yazılmamıştır.',
      price: '150',
      categories: [1, 2],
      img: 'eski-turkler.jpeg',
   },
   {
      id: '2',
      title: 'Sanat Budur',
      description: 'SanatBudur, barındırdığı absürt kara mizah ve distopik unsurlardan dolayı yepyeni bir sanat manifestosu.',
      price: '80.12',
      categories: [1, 2],
      img: 'sanat-budur.jpeg',
   },
   {
      id: '3',
      title: 'Sanat Tarihi Morfolojisine Giriş',
      description: 'Sanat Tarihi Morfolojisine Giriş, özellikle sistematik bilgi olmaksızın, sanatta nitelikli bir şey yapmanın mümkün olmayacağına işaret ediyor ve ilgilenenlere bir yol gösterme amacı taşıyor.',
      price: '25.49',
      categories: [1, 2],
      img: 'sanat-tarihi-morfolojisine-giriş.jpeg',
   },
   {
      id: '4',
      title: 'Sanat Tarihi Nasıl Yazılır ?',
      description: '“...Sanat tarihi size farklı düşünmeyi öğretir. İlginç sorular sormayı, yerleşik yanıtları ve geleneksel aklı reddetmeyi, yüzeylerin ve açık görüntülerin ötesine bakmayı, nüansları görmeyi öğretir.',
      price: '75.49',
      categories: [1, 2],
      img: 'sanat-tarihi-nasıl-yazılır.jpeg',
   },
   {
      id: '5',
      title: 'Eski Türkler',
      description: 'Netice itibariyle kadim Türkler insanlık tarihinde çok geniş ve önemli bir yer tutmuştur ama günümüze kadar bu milletin tarihi tam olarak yazılmamıştır.',
      price: '150',
      categories: [1, 3],
      img: 'eski-turkler.jpeg',
   },
   {
      id: '6',
      title: 'Sanat Budur',
      description: 'SanatBudur, barındırdığı absürt kara mizah ve distopik unsurlardan dolayı yepyeni bir sanat manifestosu.',
      price: '80.12',
      categories: [1, 3],
      img: 'sanat-budur.jpeg',
   },
   {
      id: '7',
      title: 'Sanat Tarihi Morfolojisine Giriş',
      description: 'Sanat Tarihi Morfolojisine Giriş, özellikle sistematik bilgi olmaksızın, sanatta nitelikli bir şey yapmanın mümkün olmayacağına işaret ediyor ve ilgilenenlere bir yol gösterme amacı taşıyor.',
      price: '25.49',
      categories: [1, 3],
      img: 'sanat-tarihi-morfolojisine-giriş.jpeg',
   },
   {
      id: '8',
      title: 'Sanat Tarihi Nasıl Yazılır ?',
      description: '“...Sanat tarihi size farklı düşünmeyi öğretir. İlginç sorular sormayı, yerleşik yanıtları ve geleneksel aklı reddetmeyi, yüzeylerin ve açık görüntülerin ötesine bakmayı, nüansları görmeyi öğretir.',
      price: '75.49',
      categories: [1, 3],
      img: 'sanat-tarihi-nasıl-yazılır.jpeg',
   },
   {
      id: '9',
      title: 'Sanat Tarihi Nasıl Yazılır ?',
      description: '“...Sanat tarihi size farklı düşünmeyi öğretir. İlginç sorular sormayı, yerleşik yanıtları ve geleneksel aklı reddetmeyi, yüzeylerin ve açık görüntülerin ötesine bakmayı, nüansları görmeyi öğretir.',
      price: '75.49',
      categories: [1, 4],
      img: 'sanat-tarihi-nasıl-yazılır.jpeg',
   },
   {
      id: '10',
      title: 'Sanat Tarihi Nasıl Yazılır ?',
      description: '“...Sanat tarihi size farklı düşünmeyi öğretir. İlginç sorular sormayı, yerleşik yanıtları ve geleneksel aklı reddetmeyi, yüzeylerin ve açık görüntülerin ötesine bakmayı, nüansları görmeyi öğretir.',
      price: '75.49',
      categories: [1, 4],
      img: 'sanat-tarihi-nasıl-yazılır.jpeg',
   },
   {
      id: '11',
      title: 'Sanat Tarihi Nasıl Yazılır ?',
      description: '“...Sanat tarihi size farklı düşünmeyi öğretir. İlginç sorular sormayı, yerleşik yanıtları ve geleneksel aklı reddetmeyi, yüzeylerin ve açık görüntülerin ötesine bakmayı, nüansları görmeyi öğretir.',
      price: '75.49',
      categories: [1, 4],
      img: 'sanat-tarihi-nasıl-yazılır.jpeg',
   },
   {
      id: '12',
      title: 'Sanat Tarihi Nasıl Yazılır ?',
      description: '“...Sanat tarihi size farklı düşünmeyi öğretir. İlginç sorular sormayı, yerleşik yanıtları ve geleneksel aklı reddetmeyi, yüzeylerin ve açık görüntülerin ötesine bakmayı, nüansları görmeyi öğretir.',
      price: '75.49',
      categories: [1, 4],
      img: 'sanat-tarihi-nasıl-yazılır.jpeg',
   },
   {
      id: '13',
      title: 'Sanat Tarihi Nasıl Yazılır ?',
      description: '“...Sanat tarihi size farklı düşünmeyi öğretir. İlginç sorular sormayı, yerleşik yanıtları ve geleneksel aklı reddetmeyi, yüzeylerin ve açık görüntülerin ötesine bakmayı, nüansları görmeyi öğretir.',
      price: '75.49',
      categories: [1, 5],
      img: 'sanat-tarihi-nasıl-yazılır.jpeg',
   },
   {
      id: '14',
      title: 'Sanat Tarihi Nasıl Yazılır ?',
      description: '“...Sanat tarihi size farklı düşünmeyi öğretir. İlginç sorular sormayı, yerleşik yanıtları ve geleneksel aklı reddetmeyi, yüzeylerin ve açık görüntülerin ötesine bakmayı, nüansları görmeyi öğretir.',
      price: '75.49',
      categories: [1, 5],
      img: 'sanat-tarihi-nasıl-yazılır.jpeg',
   },
   {
      id: '15',
      title: 'Sanat Tarihi Nasıl Yazılır ?',
      description: '“...Sanat tarihi size farklı düşünmeyi öğretir. İlginç sorular sormayı, yerleşik yanıtları ve geleneksel aklı reddetmeyi, yüzeylerin ve açık görüntülerin ötesine bakmayı, nüansları görmeyi öğretir.',
      price: '75.49',
      categories: [1, 5],
      img: 'sanat-tarihi-nasıl-yazılır.jpeg',
   },
   {
      id: '16',
      title: 'Sanat Tarihi Nasıl Yazılır ?',
      description: '“...Sanat tarihi size farklı düşünmeyi öğretir. İlginç sorular sormayı, yerleşik yanıtları ve geleneksel aklı reddetmeyi, yüzeylerin ve açık görüntülerin ötesine bakmayı, nüansları görmeyi öğretir.',
      price: '75.49',
      categories: [1, 5],
      img: 'sanat-tarihi-nasıl-yazılır.jpeg',
   },
   {
      id: '17',
      title: 'Sanat Tarihi Nasıl Yazılır ?',
      description: '“...Sanat tarihi size farklı düşünmeyi öğretir. İlginç sorular sormayı, yerleşik yanıtları ve geleneksel aklı reddetmeyi, yüzeylerin ve açık görüntülerin ötesine bakmayı, nüansları görmeyi öğretir.',
      price: '75.49',
      categories: [1, 6],
      img: 'sanat-tarihi-nasıl-yazılır.jpeg',
   },
   {
      id: '18',
      title: 'Sanat Tarihi Nasıl Yazılır ?',
      description: '“...Sanat tarihi size farklı düşünmeyi öğretir. İlginç sorular sormayı, yerleşik yanıtları ve geleneksel aklı reddetmeyi, yüzeylerin ve açık görüntülerin ötesine bakmayı, nüansları görmeyi öğretir.',
      price: '75.49',
      categories: [1, 6],
      img: 'sanat-tarihi-nasıl-yazılır.jpeg',
   },
   {
      id: '19',
      title: 'Sanat Tarihi Nasıl Yazılır ?',
      description: '“...Sanat tarihi size farklı düşünmeyi öğretir. İlginç sorular sormayı, yerleşik yanıtları ve geleneksel aklı reddetmeyi, yüzeylerin ve açık görüntülerin ötesine bakmayı, nüansları görmeyi öğretir.',
      price: '75.49',
      categories: [1, 6],
      img: 'sanat-tarihi-nasıl-yazılır.jpeg',
   },
   {
      id: '20',
      title: 'Sanat Tarihi Nasıl Yazılır ?',
      description: '“...Sanat tarihi size farklı düşünmeyi öğretir. İlginç sorular sormayı, yerleşik yanıtları ve geleneksel aklı reddetmeyi, yüzeylerin ve açık görüntülerin ötesine bakmayı, nüansları görmeyi öğretir.',
      price: '75.49',
      categories: [1, 6],
      img: 'sanat-tarihi-nasıl-yazılır.jpeg',
   },
]

export default booksList;